### ISSUE TITLE
Modulith together with Gradle 'org.graalvm.buildtools.native' plugin causes strange problems

### ISSUE THREAD

**Issue by dragetd** [spring-projects/spring-modulith#401] opened 2023-11-30 21:49 UTC
I have encountered a strange bug that made the modules.verify() always fail is there is a Spring component in an internal package, even if it is not used by another module, even for very simple Spring Boot applications.

My main development language is Kotlin with Gradle + Kotlin DSL. But I believe this also happens in Java. The issue seems to be with Gradle… maybe with the org.graalvm.buildtools.native plugin for gradle.

When using this plugin AND an application contextLoads() test, the modules.verify() test tails. Either removing the contextLoads() test or removing the native Plugin makes the test pass.

I struggle to understand how this happens, as I thought the plugin would only do thing when doing native builds.
I tried the same setup with Maven + Java and could not reproduce this bug.

Here is a minimal example project where you can test this behavior: https://github.com/dragetd/temp_modulith_graal_bug/tree/main

**Comment by odrotbohm** [comment] 2023-12-04 22:12
This seems to be caused by the compilation of the AOT generated code not seeing dependencies of scope `runtime`. `spring-modulith-starter-core` pulls in `spring-modulith-core` in `runtime` scope and some code generated in the AOT phase refers to types of that JAR. I'll have to investigate with our Gradle experts to find out how that can be fixed.

**Comment by odrotbohm** [comment] 2023-12-05 20:26
I filed [a ticket](https://youtrack.jetbrains.com/issue/KT-64101/Gradle-plugin-improperly-computing-classpath) with the Kotlin team.

**Comment by odrotbohm** [comment] 2023-12-05 20:26
Closing this as there's nothing we can do about this here.

**Closed by odrotbohm** 2023-12-05 20:26 UTC
Labels: resolution: invalid

**Comment by wilkinsona** [comment] 2023-12-05 20:33
Is there something to be done for the test failure that occurs with Java? The AOT processing seems to "corrupt" the state of the module such that the constraints are violated:

```
org.springframework.modulith.core.Violations: - Module 'root:com.example.modulithgraalbug' depends on non-exposed type com.example.modulithgraalbug.somemodule.internal.SomeThing__TestContext001_BeanDefinitions within module 'somemodule'!
Method <com.example.modulithgraalbug.ApplicationTests__TestContext001_BeanFactoryRegistrations.registerBeanDefinitions(org.springframework.beans.factory.support.DefaultListableBeanFactory)> calls method <com.example.modulithgraalbug.somemodule.internal.SomeThing__TestContext001_BeanDefinitions.getSomeThingBeanDefinition()> in (ApplicationTests__TestContext001_BeanFactoryRegistrations.java:56)
	at app//org.springframework.modulith.core.Violations.and(Violations.java:128)
	at java.base@17.0.9/java.util.stream.ReduceOps$1ReducingSink.accept(ReduceOps.java:80)
	at java.base@17.0.9/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base@17.0.9/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
	at java.base@17.0.9/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
	at java.base@17.0.9/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base@17.0.9/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base@17.0.9/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base@17.0.9/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base@17.0.9/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:657)
	at app//org.springframework.modulith.core.ApplicationModules.detectViolations(ApplicationModules.java:400)
	at app//org.springframework.modulith.core.ApplicationModules.verify(ApplicationModules.java:365)
	at app//com.example.modulithgraalbug.ModularityTests.verifiesModularStructure(ModularityTests.java:12)
	at java.base@17.0.9/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base@17.0.9/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base@17.0.9/java.util.ArrayList.forEach(ArrayList.java:1511)
```

**Comment by odrotbohm** [comment] 2023-12-05 21:57
In fact, there is. I didn't see that originally, as I assumed it'd be an intended violation. I think the culprit here is that the generated `…__BeanFactoryRegistrations` is located in the project root and Spring Modulith 1.1 tightened the verification to disallow code residing there to reach into the actual application modules' internals.

With manually written code this usually works well or at least can be worked around by configuration code in the application root package referring to an interface, gathering all beans of that type and the implementations hidden in the modules then implementing that interface.

I wonder if it makes sense to exclude the AOT generated files from the analysis. It looks like they all feature a double underscore in their classnames. Until we find a better means of identifying them, it might be a good enough way of detecting them?

**Comment by wilkinsona** [comment] 2023-12-06 10:29
> I wonder if it makes sense to exclude the AOT generated files from the analysis

Yes, I think it does.

> It looks like they all feature a double underscore in their classnames. Until we find a better means of identifying them, it might be a good enough way of detecting them?

Sounds reasonable to me given what's currently available.

> Do you think we could annotate these classes with `@javax.annotation.processing.Generated`?

WDYT, @snicoll? There's also `jakarta.annotation.Generated` which, judging by the package name alone, is perhaps less tied to annotation processing but may not always be on the classpath.

**Comment by snicoll** [comment] 2023-12-06 10:55
Alright, with this being the second case for us to do this, I've triaged the existing issue and put a higher priority on it, see https://github.com/spring-projects/spring-framework/issues/30824

At face value, I am not a huge fan of using any of those annotations but we can discuss the pros and cons of a custom annotation of ours in the issue. Thanks!
