### ISSUE TITLE
Add support to externalize events into AMQP only into existing exchanges

### ISSUE THREAD

**Issue by SimoneFalzone** [spring-projects/spring-modulith#922] opened 2024-11-04 08:52 UTC
When using Event Publication Registry in combination with Event externalization to RabbitMQ (AMQP), the entry in the registration for externalize listener is marked completed even when the message fails to be published to RabbitMQ.

## Setup details

Event publication registry is enabled with spring-modulith-starter-jpa library. Event externalization is setup with RabbitMQ using spring-modulith-events-amqp library.

To simulate error scenario, misconfigure the target and use a non-existing exchange name.

## Expected Behaviour

When trying to connect to a non-existing RabbitMQ exchange, the entry in the publication registry should remain incomplete.

## Actual Behaviour

When an channel error occures [see rabbitmq docs](https://www.rabbitmq.com/docs/channels#error-handling), an error log is generated (see below), but no exception is thrown, so the transaction is not rolled back.

If more information or source code is required, let me know and will add it.

## Versions
Spring Modulith 1.2.5
Spring Boot 3.3.4
JDK 21

## Logs
```
2024-11-04T09:34:25.544Z  ERROR - Shutdown Signal: channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no exchange 'non-existing-exchange' in vhost '/', class-id=60, method-id=40) - location=org.springframework.amqp.rabbit.connection.AbstractConnectionFactory$DefaultChannelCloseLogger.log(AbstractConnectionFactory.java:778) {} 
```

## Related Issues

[Issue-395](https://github.com/spring-projects/spring-modulith/issues/395)

**Comment by odrotbohm** [comment] 2024-11-04 15:48
I am not sure what we could do to prevent this on the Spring Modulith side. If the infrastructure does not throw an exception, we cannot react to it. In other words, I think this problem needs to be solved by setting up `RabbitTemplate` to properly signal such errors to clients. Unfortunately, the documentation you linked to is not particularly helpful, as it elaborates on channels being shut down but not about channels not existing in the first place. I'll make sure that someone from the Spring AMQP team will take a look, but I am afraid there's not much we can do, at least here in Spring Modulith.

**Comment by odrotbohm** [comment] 2024-11-04 16:43
A first round of investigation revealed that you should be able to get non-existing exchanges to cause messages to be rejected by both configuring `RabbitTemplate.setMandatory(true)` (you can set `spring.rabbitmq.publisherReturns` to `true` to achieve that) *and* registering a `ReturnsCallback` to produce an exception. That's essentially following how RabbitMQ works as described [here](https://www.rabbitmq.com/docs/publishers#amqp-0-9-1) and the corresponding Spring AMQP features described [here](https://docs.spring.io/spring-amqp/reference/amqp/template.html#template-confirms).

We're currently looking into whether that could be made simpler, but from the context of Spring Modulith, we're interacting with the broker as expected, so I am inclined to close this as “works as designed”. We're not dealing with a “Modulith wrongly marks publications as completed” but rather “how do I configure my AMQP client to instruct the server not to simply drop the messages”.

**Comment by SimoneFalzone** [comment] 2024-11-05 08:31
Thank you for your effort, we will have a look at your suggestions.

It would be nice if Modulith would support some features to make the setup simpler

**Comment by sfilipiak-inpost** [comment] 2024-11-13 13:05
@odrotbohm I have verified your suggestion and it doesn't work unfortunately. `ReturnsCallback` is not called when exchange does not exist, however it is called when message is not routable. Even in that case (when exception is thrown in returns callback) publication is marked as complete.

I got it to work correclty using publisher confirm mechanism to mark returned completable future as complete or completedExceptionally. This handles cases when broker doesn't accept message e.g. non-existent exchange, but it still marks unroutable messages as published (which I believe is ok). Sample ugly code provided with `spring.rabbitmq.publisher-confirm-type = correlated` and `org.springframework.modulith.events.amqp.RabbitEventExternalizerConfiguration` excluded from auto configuration.
```java
@Configuration
public class RabbitMQExternalizer {

    private final Map<CorrelationData, CompletableFuture<?>> cfs = new ConcurrentHashMap<>();

    @Bean
    RabbitTemplateCustomizer rabbitTemplateConfirmCallbackCustomizer() {
        return rabbitTemplate -> rabbitTemplate.setConfirmCallback(
                (correlationData, ack, cause) -> {
                    log.info("correlationData: {}, ack: {}, cause: {}", correlationData, ack, cause);
                    if (correlationData == null) return;
                    var cf = cfs.remove(correlationData);
                    if (cf == null) {
                        log.warn("Didn't find cf for correlationData: {}", correlationData);
                        return;
                    }
                    if (ack) {
                        log.info("Completed cf for correlationData: {}", correlationData);
                        cf.complete(null);
                        return;
                    }
                    log.info("Completed exceptionally cf for correlationData: {}", correlationData);
                    cf.completeExceptionally(new RuntimeException(cause));
                }
        );
    }

    @Bean
    DelegatingEventExternalizer rabbitAsyncEventExternalizer(EventExternalizationConfiguration configuration,
                                                        RabbitMessageOperations operations, BeanFactory factory) {

        log.debug("Registering domain event externalization to RabbitMQ…");

        var context = new StandardEvaluationContext();
        context.setBeanResolver(new BeanFactoryResolver(factory));

        return new DelegatingEventExternalizer(configuration, (target, payload) -> {

            var routing = BrokerRouting.of(target, context);
            var correlatedResult = getCorrelatedResult();

            operations.convertAndSend(routing.getTarget(), routing.getKey(payload), payload, Map.of(AmqpHeaders.PUBLISH_CONFIRM_CORRELATION, correlatedResult.getKey()));

            return correlatedResult.getValue().orTimeout(5L, TimeUnit.SECONDS);
        });
    }

    private Map.Entry<CorrelationData, CompletableFuture<?>> getCorrelatedResult() {
        CorrelationData correlationData;
        CompletableFuture<?> cf = new CompletableFuture<>();
        do {
            correlationData = new CorrelationData();
        } while (cfs.putIfAbsent(correlationData, cf) != null);
        return Map.entry(correlationData, cf);
    }

}
```

This solution would probably require some extra auto configuration. For example to handle cases where someone has already registered a confirm callback.

**Comment by SimoneFalzone** [comment] 2024-11-13 15:04
I can confirm @sfilipiak-inpost points.
I have an alternative solution using `org.springframework.amqp.rabbit.connection.CorrelationData#CorrelationData(java.lang.String).`
Which holds a `CompletableFuture with a Confirm.

Then you can either wait for it blocking, or set the value back to zero in the apply method

```
val c = correlationData.future.get(10, TimeUnit.SECONDS)
if (!c.isAck) {
    // Call DefaultEventPublicationRegistry and set completionDate to null
    logger.error { "Blocking: Message with id ${correlationData.id} was not acknowledged with reason '${c.reason}'. Message will be set to unprocessed" }
}

```
Or 

```
correlationData.future.thenApply { c ->
    if (!c.isAck) {
    logger.error { "From thenApply: Message with id ${correlationData.id} was not acknowledged with reason '${c.reason}'. Message will be set to status='Progressing'" }
}
}.exceptionally {
    logger.error(it) { "Message with id ${correlationData.id} threw exception. Message will be set to status='Progressing'" }
}
```

Unfortunately exceptionally is not set, if a channel close error occurs  e.g. 403 Forbidden or 404 Exchange not foun

**Comment by sfilipiak-inpost** [comment] 2024-11-13 15:54
I am posting vastly improved code (thanks to a deleted suggestion that `CorrelationData` already holds a `CompletableFuture<Confirm>`. It only required `spring.rabbitmq.publisher-confirm-type = correlated` to be configured and doesn't clash with any user-defined confirm callbacks.

```java
@Configuration
public class RabbitMQExternalizer {

    @Bean
    DelegatingEventExternalizer rabbitAsyncEventExternalizer(EventExternalizationConfiguration configuration,
                                                        RabbitMessageOperations operations, BeanFactory factory) {

        log.debug("Registering domain event externalization to RabbitMQ…");

        var context = new StandardEvaluationContext();
        context.setBeanResolver(new BeanFactoryResolver(factory));

        return new DelegatingEventExternalizer(configuration, (target, payload) -> {

            var routing = BrokerRouting.of(target, context);
            var correlationData = new CorrelationData();

            operations.convertAndSend(routing.getTarget(), routing.getKey(payload), payload, Map.of(AmqpHeaders.PUBLISH_CONFIRM_CORRELATION, correlationData));

            return correlationData.getFuture()
                    .orTimeout(5L, TimeUnit.SECONDS)
                    .thenCompose(this::handleConfirm);
        });
    }

    private CompletableFuture<?> handleConfirm(CorrelationData.Confirm confirm) {
        if (confirm.isAck()) {
            log.info("Completed cf");
            return CompletableFuture.completedFuture(null);
        }
        log.info("Completed exceptionally cf");
        return CompletableFuture.failedFuture(new RuntimeException(confirm.getReason()));
    }

}
```

**Comment by sfilipiak-inpost** [comment] 2024-11-20 07:17
@odrotbohm Hi, can we get some additional feedback on that issue?

**Comment by odrotbohm** [comment] 2024-12-12 08:40
My current stance is that Modulith already uses the APIs provided by Spring AMQP idiomatically. If a different, non-broker-default publication mode requires re-configuration of the AMQP client and that leads to the need to send out messages through a more specialized API in turn, I think you need to resort to implementing the externalization yourself, just like you do in the example above. Our externalization mechanism is intended to be a simple approach to publish events to brokers. I.e., `DEE` is not even considered public API. If it works for you this way, that's fine. I'm just not inclined to tweak it a lot to slightly improve the usage model in scenarios, that are not broker-idiomatic. If in doubt, you could even use `RabbitOperations` from a simple `@Async @TransactionalEventListener` directly.

That said, I still think it would make sense for you to work with the AMQP team to investigate whether they can tweak their APIs to make your scenario workable, without having to switch to a different message sending method. Then, there is probably a way to more easily flip to the mode of operation that you'd like to use, potentially hidden behind a simple switch in `application.properties`.

**Closed** 2024-12-12 08:42 UTC
Labels: in: event publication registry, resolution: works as designed

**Comment by yeahfo** [comment] 2025-03-03 05:37
On the other hand, this is a significant shortcoming of the spring-modulith event externalization. The framework should ideally handle the creation of non-existent topics/exchanges (in RabbitMQ) automatically. Otherwise, it places an inelegant burden on users to ensure these exchanges are created before startup, which can complicate deployment and maintenance processes.

**Comment by odrotbohm** [comment] 2025-03-03 17:32
I disagree. This all application domain-specific information, and we don't have a business in setting up broker infrastructure properly. It's similar to your decision, which persistence technology you'd want to use for your application. Some data stores, such as MongoDB would automatically create collections when you tell it to store data in one that doesn't exist. Relational databases, on the other hand, require some upfront creation of a schema. A task that dedicated tools exist for. Spring Modulith is not such a tool.
