### ISSUE TITLE
Spring Modulith GA releases missing on documentation page

### ISSUE THREAD

**Issue by breun** [spring-projects/spring-modulith#981] opened 2024-12-06 17:51 UTC
https://spring.io/projects/spring-modulith#learn doesn't show the [current 1.3.x GA release](https://central.sonatype.com/artifact/org.springframework.modulith/spring-modulith/versions) (currently 1.3.0).

1.2.5 is listed as being current, but if you follow the link you get the documentation for 1.3.0.

I would also expect a link to the latest 1.2.x (currently 1.2.6) and the latest 1.1.x (currently 1.1.11).

This issue looks similar to https://github.com/spring-projects/spring-modulith/issues/696.

**Comment by odrotbohm** [comment] 2024-12-10 21:46
Thanks for the heads-up. This seems to have been caused by a different website publication pipeline in place since the latest release. This should be fixed now.

**Closed by odrotbohm** 2024-12-10 21:46 UTC

**Comment by breun** [comment] 2024-12-11 10:23
Looks better now. I do see both 1.2.6 and 1.3.0 marked as current, I think that's still a bug?

**Comment by odrotbohm** [comment] 2024-12-11 14:31
Fix, of the fix applied. Thanks! 🙇
